@startuml
'https://plantuml.com/state-diagram

'hide description area for state without description
hide empty description

'CHOICE1 <<CHOICE>>
state CHOICE1 <<choice>>
note left of CHOICE1 : CHOICE1
'CHOICE2 <<CHOICE>>
state CHOICE2 <<choice>>
note left of CHOICE2 : CHOICE2
state S1
state S2
state S3
state S4
state S5
state S6


[*] -[#000000]-> S1
S1 -down[#000000]-> CHOICE1 : E1\n/ s1ToChoice
CHOICE1 -down[#000000]-> CHOICE2 : [choice2Guard]\n/ choice1ToChoice2
CHOICE2 -down[#000000]-> S6 : / choiceToS6
CHOICE2 -down[#000000]-> S5 : [s5Guard]\n/ choiceToS5
CHOICE1 -down[#000000]-> S4 : / choiceToS4
CHOICE1 -down[#000000]-> S3 : [s3Guard]
CHOICE1 -down[#000000]-> S2 : [s2Guard]\n/ choiceToS2

@enduml