@startuml
'https://plantuml.com/state-diagram

'hide description area for state without description
hide empty description

'JUNCTION1 <<JUNCTION>>
state JUNCTION1 <<start>>
'JUNCTION2 <<JUNCTION>>
state JUNCTION2 <<start>>
state S1
state S2
state S3
state S4
state S5
state S6


[*] --> S1
JUNCTION1 -down-> JUNCTION2 : [choice2Guard]\n/ choice1ToChoice2
JUNCTION1 -down-> S2 : [s2Guard]\n/ choiceToS2
JUNCTION1 -down-> S3 : [s3Guard]
JUNCTION1 -down-> S4 : / choiceToS4
JUNCTION2 -down-> S5 : [s5Guard]\n/ choiceToS5
JUNCTION2 -down-> S6 : / choiceToS6
S1 -down-> JUNCTION1 : E1\n/ s1ToChoice

note left of JUNCTION1 : JUNCTION1
note left of JUNCTION2 : JUNCTION2
@enduml