@startuml
'https://plantuml.com/state-diagram

'hide description area for state without description
hide empty description

state S1
state S2


[*] -[#000000]-> S1 : / initialAction
S1 -down[#000000]-> S2 : E1

@enduml