@startuml
'https://plantuml.com/state-diagram

'hide description area for state without description
hide empty description

state S1
state S2
state S3
state S4
'choice1 <<CHOICE>>
state choice1 <<choice>>
note left of choice1 : choice1


[*] --> S1
S1 -down-> choice1 : E1
choice1 -down-> S2 : [s2Guard]
choice1 -down-> S3 : [s3Guard]
choice1 -down-> S4

@enduml