@startuml
'https://plantuml.com/state-diagram

'hide description area for state without description
hide empty description

state S1
S1 : /do e1Action
state S2
S2 : /do e2Action
state S3


[*] -[#000000]-> S1
S1 -down[#000000]-> S2 : E1
S2 -down[#000000]-> S3 : E2

@enduml