@startuml
note "!!! NOT WORKING !!!\n!!! duplicated transition: 'S3 -down[#000000]-> S4 : E2' !!!\n??? Error in Spring Statemachine UML parser ???\n see [[https://github.com/spring-projects/spring-statemachine/issues/1141]] " as NOT_WORKING
'https://plantuml.com/state-diagram

'hide description area for state without description
hide empty description

state null  {
  state S1
  state S2


  [*] -[#000000]-> S1
  S1 -down[#000000]-> S2 : E1
  state S3
  state S4


  [*] -[#000000]-> S3
  S3 -down[#000000]-> S4 : E2
}


[*] -[#000000]-> null

@enduml