@startuml
'https://plantuml.com/state-diagram

'hide description area for state without description
hide empty description

state S1
state S2  {
  state S21
  state S22


  [*] --> S21
  state ENTRY <<entryPoint>>
  state EXIT <<exitPoint>>
}
state S3
state S4


[*] --> S1
ENTRY -down-> S22
EXIT -down-> S4
S1 -down-> ENTRY : E3
S1 -down-> S2 : E1
S22 -down-> EXIT : E4
S2 -down-> S3 : E2

@enduml