@startuml
'https://plantuml.com/state-diagram

'hide description area for state without description
hide empty description

state S1
S1 : E2 /defer
state S2
state S3


[*] --> S1
S1 -down-> S2 : E1
S2 -down-> S3 : E2

@enduml