@startuml
'https://plantuml.com/state-diagram

'hide description area for state without description
hide empty description

state S1
state S2  {
  state S20
  state S21  {
    state S30
    state S31


    [*] --> S30
  }


  [*] --> S20
}
state S3


[*] --> S1
S1 -down-> S2 : E1
S20 -down-> S21 : E2
S30 -down-> S31 : E3
S2 -down-> S3 : E4

@enduml