@startuml
'https://plantuml.com/state-diagram

'hide description area for state without description
hide empty description

state S1
state S2  {
  state S20
  state S21


  [*] --> S20
}


[*] --> S1
S1 -down-> S2 : E1
S20 -down-> S21 : E2
S2 -down-> S1 : E3
'S1 -> SH
S1 -down-> S2[H] : E4

@enduml