@startuml
'https://plantuml.com/state-diagram

'hide description area for state without description
hide empty description

'CHOICE <<CHOICE>>
state CHOICE <<choice>>
state S1
state S2
state S3
state S4


[*] --> S1
CHOICE -down-> S2 : [s2Guard]
CHOICE -down-> S3 : [s3Guard]
CHOICE -down-> S4
S1 -down-> CHOICE : E1

note left of CHOICE : CHOICE
@enduml