@startuml
'https://plantuml.com/state-diagram

'hide description area for state without description
hide empty description

state S1
state S2  {
  state S20
  state S21  {
    state S211
    state S212


    [*] -[#000000]-> S211
  }


  [*] -[#000000]-> S20
}


[*] -[#000000]-> S1
S211 -down[#000000]-> S212 : E2
S212 -down[#000000]-> S1 : E3
S1 -down[#000000]-> S211 : E1
'S1 -> SH
S1 -down[#000000]-> S2[H*] : E4

@enduml