@startuml
'https://plantuml.com/state-diagram

'hide description area for state without description
hide empty description

state S1
state S2
state S3
S3 : /entry s3Entry
state S4
state S5
S5 : /entry s5Entry


[*] --> S1
S1 -down-> S2 : E1
S1 -down-> S4 : E2
S2 -down-> S3 : every 1 second
S4 -down-> S5 : after 1 second

@enduml